name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/gradle-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}

  dropbox:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/dropbox-publish-artifact.yml@main
    if: github.ref == ${{ github.event.repository.default_branch }}
    needs:
      - build
    with:
      artifact: Gradle-Libs
      source: "mediaconverter-shaded.jar"
      target: "/Documents/JARs/MediaConverter.jar"
    secrets:
      dropbox-token: ${{ secrets.DROPBOX_TOKEN }}
