name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 20

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Build
        uses: gradle/gradle-build-action@v2.6.1
        with:
          cache-disabled: true
          arguments: |
            check
            build
            -Dorg.gradle.project.githubRepoUsername="RakSrinaNa"
            -Dorg.gradle.project.githubRepoPassword="${{ secrets.GITHUB_TOKEN }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shadow-jar
          path: build/libs/mediaconverter-shaded.jar

  dropbox:
    name: Deploy on Dropbox
    concurrency: dropbox
    runs-on: ubuntu-latest
    needs: build
    if: contains('refs/heads/main', github.ref)
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: shadow-jar
      - name: Deploy on Dropbox
        uses: deka0106/upload-to-dropbox@v2.0.1
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_DEPLOY_TOKEN }}
          src: "mediaconverter-shaded.jar"
          dest: "/Documents/JARs/MediaConverter.jar"
          mode: overwrite
